---

- include: setup_logging.yml
  tags: logging

- include: setup_gunicorn.yml
  tags: gunicorn

#- include: setup_django_app.yml
#  tags: deploy

- include: set_file_permissions.yml
  tags: deploy

- include: setup_nginx.yml
  tags: nginx

- include: setup_git_repo.yml
  tags: deploy

- include: setup_supervisor.yml
  tags: supervisor