---

- name: Create the application log folder
  file: path="{{ application_log_dir }}"
        owner="{{ application_name }}"
        group="{{ application_group }}"
        mode=0774
        state=directory

- name: Create the nginx log folder
  file: path="{{ logs_directory }}/nginx"
        owner="{{ application_name }}"
        group="{{ application_group }}"
        mode=0774
        state=directory

- name: Create the nginx error log file
  command: touch "{{ nginx_log_file }}"
           creates="{{ nginx_log_file }}"

- name: Create the nginx access log file
  command: touch "{{ nginx_access_file }}"
           creates="{{ nginx_access_file }}"

- name: Create the django error log file
  command: touch "{{ django_log_file }}"
           creates="{{ django_log_file }}"

- name: Create the django access log file
  command: touch "{{ django_access_file }}"
           creates="{{ django_access_file }}"           

- name: Create the tilestache error log file
  command: touch "{{ tilestache_log_file }}"
           creates="{{ tilestache_log_file }}"

- name: Create the tilestache access log file
  command: touch "{{ tilestache_access_file }}"
           creates="{{ tilestache_access_file }}"     

- name: Set permission to the django log file
  file: path="{{ django_log_file }}"
        owner="{{ application_name }}"
        group="{{ application_group }}"
        mode=0664
        state=file

- name: Set permission to the django access log file
  file: path="{{ django_access_file }}"
        owner="{{ application_name }}"
        group="{{ application_group }}"
        mode=0664
        state=file

- name: Set permission to the tilestache log file
  file: path="{{ tilestache_log_file }}"
        owner="{{ application_name }}"
        group="{{ application_group }}"
        mode=0664
        state=file

- name: Set permission to the tilestache accesslog file
  file: path="{{ tilestache_access_file }}"
        owner="{{ application_name }}"
        group="{{ application_group }}"
        mode=0664
        state=file

- name: Set permission to the nginx log file
  file: path="{{ nginx_log_file }}"
        owner="{{ application_name }}"
        group="{{ application_group }}"
        mode=0664
        state=file

- name: Set permission to the nginx accesslog file
  file: path="{{ nginx_access_file }}"
        owner="{{ application_name }}"
        group="{{ application_group }}"
        mode=0664
        state=file
        
