---

- name: Create the Supervisor config file
  template: src="supervisor_config.j2 dest=/etc/supervisor/conf.d/{{ project_name }}.conf" backup=yes

- name: Re-read the Supervisor config files
  supervisorctl: name=tilestache state=present

- name: Restart Supervisor
  supervisorctl: name=tilestache state=restarted
