---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv="{{ virtualenv_path }}"
       requirements={{ requirements_file }}

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}/{{ project_name }}"
    virtualenv: "{{ virtualenv_path }}"
  tags: django.migrate

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}/{{ project_name }}"
    virtualenv: "{{ virtualenv_path }}"
  tags: django.collectstatic
