---

# Application settings.
project_path: "{{ website_directory }}"
application_log_dir: "{{ logs_directory }}/gunicorn"
django_log_file: "{{ application_log_dir }}/django_error.log"
django_access_file: "{{ application_log_dir }}/django_access.log"
initial_data: "{{ project_path }}/{{ project_name }}/initial_data/db.json"
tilestache_log_file: "{{ application_log_dir }}/tilestache_error.log"
tilestache_access_file: "{{ application_log_dir }}/tilestache_access.log"
nginx_log_file: "{{ logs_directory }}/nginx/nginx_error.log"
nginx_access_file: "{{ logs_directory }}/nginx/nginx_access.log"
requirements_file: "{{ project_path }}/requirements.txt"


# Gunicorn settings
gunicorn_user: "{{ application_name }}"
gunicorn_password: "{{ application_password }}"
gunicorn_group: "{{ application_group }}"
# Gunicorn settings. For the number of workers, a good rule to follow is
# 2 x number of CPUs + 1
gunicorn_num_workers: 5

# Setting this to 1 will restart the Gunicorn process each time
# you make a request, basically reloading the code. Very handy
# when developing. Set to 0 for unlimited requests (default).
gunicorn_max_requests: 0

gunicorn_timeout_seconds: 300

# Nginx settings
nginx_http_port: 80
nginx_https_port: 443
nginx_static_dir: "{{ website_directory }}/{{ project_name }}/assets/"
nginx_media_dir: "{{ website_directory }}/{{ project_name }}/media/"


# Django Environment variables
django_environment:
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
