---

# Application settings.
project_path: "{{ website_directory }}"
application_log_dir: "{{ logs_directory }}/gunicorn"
django_log_file: "{{ application_log_dir }}/gunicorn_django_error.log"
django_access_file: "{{ application_log_dir }}/gunicorn_django_access.log"
tilestache_log_file: "{{ application_log_dir }}/gunicorn_tilestache_error.log"
tilestache_access_file: "{{ application_log_dir }}/gunicorn_tilestache_access.log"
nginx_log_file: "{{ logs_directory }}/nginx/nginx_error.log"
nginx_access_file: "{{ logs_directory }}/nginx/nginx_access.log"
requirements_file: "{{ project_path }}/requirements.txt"


# Gunicorn settings
gunicorn_user: "{{ application_name }}"
gunicorn_password: "{{ application_password }}"
gunicorn_group: "{{ application_group }}"

# Nginx settings
nginx_http_port: 80
nginx_https_port: 443
nginx_static_dir: "{{ virtualenv_path }}/static/"
nginx_media_dir: "{{ virtualenv_path }}/media/"


# Django Environment variables
django_environment:
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
