---

git_repo: git@bitbucket.org:integratedsustainability/isc_website.git

project_name: tilefarm
application_name: webuser
application_group : webapps
application_password: $1$salty$SzJsU4qDcXp536Acnlp6I. #password see: https://github.com/ansible/ansible/issues/2305

mapping_directory: "/webapps/tilefarm"
website_directory: "/webapps/website"
logs_directory: "/webapps/logs"

gunicorn_user: "{{ application_name }}"
gunicorn_password: "{{ application_password }}"

virtualenv_name: tilefarm
virtualenv_path: "/virtualenv/{{ virtualenv_name }}"

standard_user: admin
standard_pw: password