---

- name: Create the folder for the celery scripts
  file: path={{ celery_scripts_dir }}
        owner={{ celery_user }}
        group={{ celery_group }}
        mode=0774
        state=directory
  tags:
    - celery