---

- name: install celery and flower
  pip: virtualenv={{ virtualenv_path }} name={{ item }} virtualenv_site_packages=yes
  with_items:
    - celery
    - flower

- name: Create the {{ celery_application_name }} log directory
  file: path={{ celery_log_dir }}
        owner={{ celery_user }}
        group={{ celery_group }}
        state=directory
  tags:
    - celery

- name: Create the {{ celery_application_name }} log file
  file: path={{ celery_log_file }}
        owner={{ celery_user }}
        group={{ celery_group }}
        state=touch
  tags:
    - celery
