---
- name: Update apt with postgres 94 key
  apt_key: url=http://www.postgresql.org/media/keys/ACCC4CF8.asc 
           state=present
  tags: packages

- name: Update apt with postgres 94
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' 
                  update_cache={{ update_apt_cache }}
                  state=present
  tags: packages

- name: Install PostgreSQL
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - postgresql-9.4
    - postgresql-contrib
    - python-psycopg2
    - postgis
  tags: packages

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  sudo_user: postgres
  postgresql_db: name={{ db_name }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present

# Create superuser
- name: Ensure user has access to the database
  sudo_user: postgres
  postgresql_user: db={{ db_name }}
                   name={{ standard_user }}
                   password={{ standard_pw }}
                   priv=ALL
                   state=present

- name: Ensure user has necessary privileges
  sudo_user: postgres
  postgresql_user: name={{ standard_user }}
                   role_attr_flags=SUPERUSER,CREATEDB,LOGIN
                   state=present

# Create webuser
- name: Ensure user has access to the database
  sudo_user: postgres
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   state=present
                   
- name: Ensure PostgreSQL is listening on all localhost
  lineinfile: dest=/etc/postgresql/9.4/main/postgresql.conf
              regexp='^#?listen_addresses\s*='
              line="listen_addresses = '127.0.0.1'"
              state=present
  notify: restart postgresql   

- lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf
              regexp='host\s+all\s+all\s+127.0.0.1/32\s+md5'
              line='host all all 127.0.0.1/32 md5'
               insertbefore=BOF
  notify: restart postgresql  

- name: Ensure user has necessary privileges
  sudo_user: postgres
  postgresql_user: name={{ db_user }}
                   role_attr_flags=CREATEDB,LOGIN
                   state=present

- name: enable postgis extension 
  sudo_user: postgres
  command: psql -d {{ db_name }} -c "CREATE EXTENSION postgis;"
                   
