---

- name: Create the application user
  user: name={{ application_name }} password={{ application_password }} state=present shell=/bin/bash

- name: Create the application group
  group: name={{ application_group }} system=yes state=present

- name: Add the application user to the application group
  user: name={{ application_name }} group={{ application_group }} state=present

- name: Create a ssh Directory
  file: path=/home/{{ application_name }}/.ssh
        recurse=yes
        state=directory
        mode=0700
        owner="{{ application_name }}"
        group="{{ application_group }}"